{{- if and (not .Values.auth.existingSecret) (or (eq .Values.auth.type "password") (eq .Values.auth.type "totp")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copycat.authSecretName" . }}
  labels:
    {{- include "copycat.labels" . | nindent 4 }}
type: Opaque
stringData:
  COPYCAT_USERNAME: {{ .Values.auth.username | quote }}
  COPYCAT_PASSWORD: {{ .Values.auth.password | quote }}
  COPYCAT_SECRET_KEY: {{ .Values.auth.secretKey | quote }}
  {{- if eq .Values.auth.type "totp" }}
  COPYCAT_TOTP_KEY: {{ .Values.auth.totpKey | quote }}
  {{- end }}
{{- end }}
